DELIVERY_SYSTEM_MAP = {
    "IHUB-HK2": "HongKong",
    "VIENNA": "AAH",
    "BRDWH": "Brazil",
    "IHUB-CN1": "China",
    "IHUB-SG1": "Singapore",
    "IHUB-AU1": "Australia",
    "IHUB-DE2": "Germany",
    "IHUB-US1": "UnitedStates",
    "IHUB-BE1": "Belgium",
    "IHUB-FR1": "France",
    "LEASE": "Lease",
    "ALFAM": "Alfam",
    "FBS": "Main Bank",
    "ACF-UK": "ACF",
    "ACF-FR": "ACF",
    "ACF-NL": "ACF",
    "ACF-DE": "ACF",
    "AACF": "ACF",
}
